language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

sudo: false

matrix:
  allow_failures:
    - python: "pypy3"


script:
  - coverage run $(which py.test)
  - flake8 pysyncthing
