language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

sudo: false

cache:
  directories:
    - $HOME/wheelhouse

matrix:
  allow_failures:
    - python: "pypy3"

install:
  - pip wheel -r requirements.txt --wheel-dir=$HOME/wheelhouse
  - pip install --no-index --find-links=$HOME/wheelhouse -r requirements.txt

script:
  - coverage run $(which py.test)
  - flake8 pysyncthing
